# all commands by default will run on every push, not every commit
default_install_hook_types: [pre-push]
default_stages: [push]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.2.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-snowflake==1.4.5',
          'sqlfluff-templater-dbt==1.2.1'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-snowflake==1.4.5',
          'sqlfluff-templater-dbt==1.2.1'
        ]

